const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('clop', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (s) => ipcRenderer.invoke('settings:set', s),
  getChats: () => ipcRenderer.invoke('chats:get'),
  setChats: (c) => ipcRenderer.invoke('chats:set', c),
  openFolder: () => ipcRenderer.invoke('dialog:openFolder'),
  listDir: (p) => ipcRenderer.invoke('fs:list', p),
  readFile: (p) => ipcRenderer.invoke('fs:read', p),
  writeFile: (p, c) => ipcRenderer.invoke('fs:write', p, c),
  chat: (payload) => ipcRenderer.invoke('ai:chat', payload),
  cliDetect: () => ipcRenderer.invoke('cli:detect'),
  ollamaModels: () => ipcRenderer.invoke('ollama:models'),
  openExternal: (u) => ipcRenderer.invoke('shell:open', u),
  version: () => ipcRenderer.invoke('app:version'),
  projectsRoot: () => ipcRenderer.invoke('projects:root'),
  stop: (reqId) => ipcRenderer.invoke('ai:stop', reqId),
  onDelta: (cb) => ipcRenderer.on('ai:delta', (_e, payload) => cb(payload)),
  onActivity: (cb) => ipcRenderer.on('ai:activity', (_e, payload) => cb(payload)),
  readFileB64: (p) => ipcRenderer.invoke('fs:readb64', p),
  attachSave: (name, base64) => ipcRenderer.invoke('attach:save', name, base64),
  getFilePath: (file) => webUtils.getPathForFile(file),
  termStart: (cwd) => ipcRenderer.invoke('term:start', cwd),
  termInput: (s) => ipcRenderer.invoke('term:input', s),
  termKill: () => ipcRenderer.invoke('term:kill'),
  onTermData: (cb) => ipcRenderer.on('term:data', (_e, s) => cb(s)),
  gitInfo: (dir) => ipcRenderer.invoke('git:info', dir),
  gitDiff: (dir, file) => ipcRenderer.invoke('git:diff', dir, file),
  gitCommit: (dir, msg) => ipcRenderer.invoke('git:commit', dir, msg),
  gitInit: (dir) => ipcRenderer.invoke('git:init', dir),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  artverSave: (p) => ipcRenderer.invoke('artver:save', p),
  artverList: (p) => ipcRenderer.invoke('artver:list', p),
  artverRead: (p, ts) => ipcRenderer.invoke('artver:read', p, ts),
  artverRestore: (p, ts) => ipcRenderer.invoke('artver:restore', p, ts)
});
